### ISSUE TITLE
nks.kr.private-ncr.gov-ntruss.com 의 Self-Signed Certificate 사용으로 인한 Image Pull Error

### ISSUE THREAD

**Issue by a3626a** [NaverCloudPlatform/nks-alb-ingress-controller#24]
https://guide-gov.ncloud-docs.com/docs/k8s-k8suse-albingress
위 문서를 따라 NKS 클러스터에 alb ingress controller 를 설치하는 과정에서 문제가 발생하여 공유드립니다.

아직 제 개인적인 설정의 문제인지, NCP의 문제인지는 명확하지는 않습니다.

---

NKS에 설치한 Pod가 뜨는 과정에서 다음과 같은 오류가 발생했습니다.
```
Failed to pull image "nks.kr.private-ncr.gov-ntruss.com/alb-ingress-controller:0.7.3": rpc error: code = Unknown desc = failed to pull and unpack image "nks.kr.private-ncr.gov-ntruss.com/alb-ingress-controller:0.7.3": failed to resolve reference "nks.kr.private-ncr.gov-ntruss.com/alb-ingress-controller:0.7.3": failed to do request: Head "https://nks.kr.private-ncr.gov-ntruss.com/v2/alb-ingress-controller/manifests/0.7.3": x509: certificate is valid for ingress.local, not nks.kr.private-ncr.gov-ntruss.com
```

이 Pod를 띄운 Deployment는 다음과 같습니다.

> 이 과정에서 문서에 제시된 `install.yaml`을 그대로 따르지 않았습니다. Helm 을 사용하기 위해 수정됐습니다.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nks-alb-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nks-alb-ingress-controller
    app.kubernetes.io/version: 1.16.0
    argocd.argoproj.io/instance: nks-alb-ingress-controller
    helm.sh/chart: nks-alb-ingress-controller-0.1.0
  name: nks-alb-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nks-alb-ingress-controller
      app.kubernetes.io/name: nks-alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nks-alb-ingress-controller
        app.kubernetes.io/name: nks-alb-ingress-controller
    spec:
      containers:
        - args:
            - '--api-url=nks.apigw.gov-ntruss.com'
            - '--base-path=/ncloud/v1'
            - '--ingress-class=ncloud.com/alb'
            - '--enable-leader-election=true'
          command:
            - /alb-ingress-controller
          image: 'nks.kr.private-ncr.gov-ntruss.com/alb-ingress-controller:0.7.3'
          imagePullPolicy: IfNotPresent
          name: nks-alb-ingress-controller
          resources:
            limits:
              cpu: 100m
              memory: 180Mi
            requests:
              cpu: 100m
              memory: 90Mi
          securityContext: {}
      securityContext: {}
      serviceAccountName: alb-ingress-controller
```

제 설정의 문제라고 판단되지는 않아 클러스터 내부에 임의의 Pod를 띄우고 `wget`을 활용하여 문제를 확인해보았습니다.

> Docker의 프로토콜에 의거하여 nks.kr.private-ncr.gov-ntruss.com/alb-ingress-controller 에 pull을 치면 `https://nks.kr.private-ncr.gov-ntruss.com/v2/alb-ingress-controller/manifests/0.7.3` 로 요청이 발생하는 것으로 파악하여 이곳에 요청을 넣었습니다.

```
wget https://nks.kr.private-ncr.gov-ntruss.com/v2/alb-ingress-controller/manifests/0.7.3
--2023-10-16 10:35:31--  https://nks.kr.private-ncr.gov-ntruss.com/v2/alb-ingress-controller/manifests/0.7.3
Resolving nks.kr.private-ncr.gov-ntruss.com (nks.kr.private-ncr.gov-ntruss.com)... 169.254.170.176
Connecting to nks.kr.private-ncr.gov-ntruss.com (nks.kr.private-ncr.gov-ntruss.com)|169.254.170.176|:443... connected.
ERROR: cannot verify nks.kr.private-ncr.gov-ntruss.com's certificate, issued by 'CN=Kubernetes Ingress Controller Fake Certificate,O=Acme Co':
  Self-signed certificate encountered.
ERROR: no certificate subject alternative name matches
        requested host name 'nks.kr.private-ncr.gov-ntruss.com'.
To connect to nks.kr.private-ncr.gov-ntruss.com insecurely, use `--no-check-certificate'.
```

앞선 오류 로그보다 보다 자세한 문제를 확인할 수 있습니다. 이 결과에 따르면 `nks.kr.private-ncr.gov-ntruss.com` 자체가 적절한 절차로 발급된 인증서가 아니고, Self-signed 인증서라서 보안 문제로 통과가 안되는 것으로 판단됩니다.

docker나 pod 설정을 통해 insecure mode를 켜면 배포는 가능할 것으로 생각되지만, 이게 NCP에서 의도한 방향이 맞을까요?
