### ISSUE TITLE
Yorkie Cluster 설치중 발생한 이슈 문의

### ISSUE THREAD

**Issue by hackerwins** [NaverCloudPlatform/nks-alb-ingress-controller#31]
안녕하세요.

NCP에 [Yorkie Cluster](https://github.com/yorkie-team/yorkie/tree/main/build/charts/yorkie-cluster) 설치하는 중에 ALB Ingress Controller를 이용해서 로드밸런서를 연결하면서 몇 가지 이슈 발생해서 문의드립니다.

### A. Ingress 대상 Service를 ExternalName 타입 지원 이슈

Ingress의 대상 서비스를 ExternalName 으로 지정하면, NodePort를 찾을 수 없다는 오류 발생합니다.

```sh
failed to reconcile rules: failed to get ingress rules: failed to parse ingress rule (priority: 1): failed to update ingress rule by service port: failed to build ingress target group: cannot found nodeport: yorkie/istio-ingressgateway/servicePort:{0 80}
```

대략적인 통신 구조는 아래와 같습니다.

```
yorkie.yorkie<Ingress> - yorkie.istio-ingressgateway<Service.ExternalName> - istio-system.istio-ingressgateway<Service>
```

현재는 ExternalName을 사용하지 않도록 수정한 상태입니다.
https://github.com/yorkie-team/yorkie/pull/834#issuecomment-2039023474

### B. `alb.ingress.kubernetes.io/enable-http2` 활성화시 오류 발생

enable-http2를 활성화 시키면 아래와 같은 오류가 발생합니다.

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.annotations of type string
```

### C. 배경상황
현재 Yorkie Cluster는 AWS에서 운영중이고 NCP 운영 이전을 고려하고 있습니다. 추가로 AWS ALB에서 설정했던 옵션을 NCP ALB에 대응해서 설정중입니다.

```yaml
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Set alb.ingress.kubernetes.io/certificate-arn annotation to TLS certificate's ARN issued in AWS ACM 
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.hosts.apiHost }}
    alb.ingress.kubernetes.io/group.order: '10'
```

- https://github.com/yorkie-team/yorkie/blob/d5bc939acadc0008e9be1998dc70bb1e0ea87902/build/charts/yorkie-cluster/templates/istio/ingress.yaml#L8-L15
- https://guide.ncloud-docs.com/docs/k8s-k8suse-albingress#alb-ingress-controller-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98

**Comment by krapie** [comment]
> B. alb.ingress.kubernetes.io/enable-http2 활성화시 오류 발생

이 문제는 `alb.ingress.kubernetes.io/enable-http2` 값을 ""로 감싸주지 않아서 Go struct 생성 시에 unmarshal을 못해서 발생하는 것 같아요.


```yaml
// AS-IS
alb.ingress.kubernetes.io/enable-http2: true

// TO-BE
alb.ingress.kubernetes.io/enable-http2: "true"
```

**Comment by simang** [comment]
@hackerwins 안녕하세요. 답변이 늦어져서 죄송합니다.

`ExternalName` type의 Service는 ALB에서 사용할 수 없는 Endpoint여서 `NodePort`로만 연결이 가능합니다.
`ExternalName`을 사용하신 의도가 하나의 ingress(ALB)에서 다른 네임스페이스에 존재하는 Service로 라우팅하기 위한것으로 생각되는데요.
AWS에는 ingress group이 있지만 저희는 아직 대응되는 기능이 없는 상태입니다.
따라서 현재로서는 이슈를 해결할 방법이 공식적으로는 없는 상황입니다 ㅠ

다만 한가지 우회 방안은 있는데요.
Ingress와 다른 네임스페이스에 존재하는 서비스(**A**)를 `NodePort` type으로 먼저 생성하고
Ingress 네임스페이스에 위치한 `ExternalName` type의 서비스(**B**)에 nodePort값을 위 **A** 서비스의 nodePort값과 동일한 값으로 넣으면 실제로는 동작하지 않는 무의미한 값이지만 값이 그대로 저장이 됩니다.(모든 버전에서 가능한지는 모르겠습니다.)
위 처럼 하면 alb-ingress-controller에서는 `ExternalName` 서비스에 존재하는 nodeport값을 가져와서 target group 생성을 수행하게 되고 실제로는 **A** 서비스에 대해 target group이 생성되는 결과가 됩니다.

아래는 예전에 테스트 했던 예시입니다.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: naver-svc
  namespace: naver
spec:
  type: NodePort
  selector:
    app: naver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30430
---
apiVersion: v1
kind: Service
metadata:
  name: naver-headless
spec:
  type: ExternalName
  externalName: naver-svc.naver.svc.cluster.local
  ports:
  - port: 80 
    targetPort: 80 
    nodePort: 30430
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: naver-headless
            port:
              number: 80
```

위 같은 형태로 사용하셔도 괜찮으시다면 참고 부탁드리며
관련 기능도 빠른 시일내로 개발 하도록 하겠습니다.
